Create and show tricks
ThomasG51/snow-tricks pull request #25
Opened 2021-02-04 17:54 UTC by ThomasG51

2021-02-05 16:41 UTC, TBoileau requested changes
ajouter .idea dans gitignore

2021-02-05 16:41 UTC, TBoileau commented on src/Controller/TricksController.php
> +        $tricks = new Tricks();
Une entité est toujours au singulier

2021-02-05 16:41 UTC, TBoileau commented on src/Controller/TricksController.php
> +        $formMedia = $this->createForm(MediaType::class, $media);
Ce formulaire est inutile

2021-02-05 16:41 UTC, TBoileau commented on src/Entity/Media.php
> +     * @ORM\ManyToOne(targetEntity=Tricks::class)
Il manque la bi-directionnalité

2021-02-05 16:41 UTC, TBoileau commented on src/Form/TricksType.php
> +class TricksType extends AbstractType
à mettre au singulier

2021-02-06 21:06 UTC, ThomasG51 commented on src/Controller/TricksController.php
> +        $tricks = new Tricks();
entité modifié

2021-02-06 21:06 UTC, ThomasG51 commented on src/Controller/TricksController.php
> +        $formMedia = $this->createForm(MediaType::class, $media);
formulaire supprimé

2021-02-06 21:07 UTC, ThomasG51 commented on src/Form/TricksType.php
> +class TricksType extends AbstractType
nom du formulaire modifié

2021-02-11 19:57 UTC, merged