Handle videos collection
ThomasG51/snow-tricks pull request #27
Opened 2021-02-12 18:16 UTC by ThomasG51

2021-03-12 18:47 UTC, TBoileau approved these changes

2021-03-12 18:47 UTC, TBoileau commented on src/Controller/TricksController.php
> +    public function show($id, TrickRepository $trickRepository, Request $request, EntityManagerInterface $manager): Response
Pas besoin d'injecter EM car tu l'as déjà dans l'AbstractController => `$thsi->getDoctrine()->getManager()`

2021-03-12 18:47 UTC, TBoileau commented on src/Controller/RegistrationController.php
> +    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, LoginFormAuthenticator $authenticator, EntityManagerInterface $m
Pas besoin d'injecter EM car tu l'as déjà dans l'AbstractController => `$thsi->getDoctrine()->getManager()`

2021-03-12 20:44 UTC, ThomasG51 commented on src/Controller/TricksController.php
> +    public function show($id, TrickRepository $trickRepository, Request $request, EntityManagerInterface $manager): Response
modification faite

2021-03-12 20:45 UTC, ThomasG51 commented on src/Controller/TricksController.php
> +    public function show($id, TrickRepository $trickRepository, Request $request, EntityManagerInterface $manager): Response
modification faite

2021-03-12 20:47 UTC, ThomasG51 commented on src/Controller/RegistrationController.php
> +    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder, GuardAuthenticatorHandler $guardHandler, LoginFormAuthenticator $authenticator, EntityManagerInterface $m
Modification faite

2021-03-26 18:00 UTC, TBoileau requested changes

2021-03-26 22:04 UTC, ThomasG51 commented on src/Controller/TricksController.php
> +                $video->setUrl($url);
regex implementee

2021-03-26 22:05 UTC, ThomasG51 commented on src/Form/TrickType.php
> +    }
nettoyage effectue

2021-03-26 22:05 UTC, ThomasG51 commented on src/Repository/ResetPasswordRequestRepository.php
> +    */
nettoyage effectué

2021-03-26 22:06 UTC, merged