Trick handler
ThomasG51/snow-tricks pull request #33
Opened 2021-03-28 00:22 UTC by ThomasG51

2021-04-02 17:02 UTC, TBoileau requested changes

2021-04-02 17:02 UTC, TBoileau commented on src/Handler/CreateCommentHandler.php
> +    private  $formComment;
Tu peux le typer `FormInterface`

2021-04-02 17:02 UTC, TBoileau commented on src/Handler/CreateCommentHandler.php
> +        $this->formComment->handleRequest($request);
tu peux chaîner les appel `$this->formComment = $this->formFactory->create(CommentType::class, $comment)->handleRequest($request);`

2021-04-02 17:02 UTC, TBoileau commented on src/Handler/CreateCommentHandler.php
> +            $comment->setTrick($trick);
A supprimer, puisque gérer dans le contrôleur

2021-04-02 17:02 UTC, TBoileau commented on src/Handler/EditTrickHandler.php
> +    private $formTrick;
Memê remarque que CreateTrickHandler

2021-04-02 17:02 UTC, TBoileau commented on src/Handler/EditTrickHandler.php
> +        $this->formTrick->handleRequest($request);
Memê remarque que CreateTrickHandler

2021-04-02 17:02 UTC, TBoileau commented on src/Handler/EditTrickHandler.php
> +            $this->manager->persist($trick);
Pas besoin de persist

2021-04-02 20:45 UTC, ThomasG51 commented on src/Controller/TricksController.php
>          $trick = $trickRepository->findOneBySlug($slug);
injection du trick

2021-04-02 20:46 UTC, ThomasG51 commented on src/Controller/TricksController.php
>          $comment = new Comment();
set du trick dans le controller

2021-04-09 16:24 UTC, TBoileau approved these changes

2021-04-09 16:29 UTC, merged